c=open("frontend/app/analytics/page.tsx",encoding="utf-8").read()
c=c.replace("  const [savingTarget, setSavingTarget] = useState(false);","  const [savingTarget, setSavingTarget] = useState(false);\n  const [rejectedQuotes, setRejectedQuotes] = useState<any[]>([]);\n  const [allQuotes, setAllQuotes] = useState<any[]>([]);\n  const [suppliers, setSuppliers] = useState<any[]>([]);",1)
c=c.replace("]).then(([{ data: s }, { data: r }, { data: e }, { data: t }, { data: q }, { data: sup }]) => {","]).then(([{ data: s }, { data: r }, { data: e }, { data: t }, { data: q }, { data: sup }]) => {\n        setRejectedQuotes((q || []).filter((x: any) => x.rejected));\n        setAllQuotes(q || []);\n        setSuppliers(sup || []);",1)
open("frontend/app/analytics/page.tsx","w",encoding="utf-8").write(c)
print("Done:", "rejectedQuotes" in c, "setAllQuotes" in c)
