c=open("frontend/app/admin/page.tsx",encoding="utf-8").read()
i=c.find("const defaults")
print("has defaults already:", i>0)
i2=c.find("Hi ${name}! We are actively")
print("searching msg at:", i2)
print(repr(c[i2-50:i2+100]))
